import { LegalPage, type LegalSection } from "@/components/site/legal-page";

export const metadata = { title: "Terms & Conditions" };

const sections: LegalSection[] = [
  {
    title: "Acceptance of terms",
    items: [
      {
        label: "Agreement:",
        text: "By accessing or using Socrate, you agree to be bound by these Terms & Conditions. If you do not agree, please do not use the service.",
      },
      {
        label: "Changes:",
        text: "We may update these terms from time to time. Continued use of Socrate after changes means you accept the new terms.",
      },
    ],
  },
  {
    title: "Use of the service",
    items: [
      {
        label: "Eligibility:",
        text: "You must be at least 13 years old to use Socrate. If you are under 18, you must have parental consent.",
      },
      {
        label: "Account responsibility:",
        text: "You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account.",
      },
      {
        label: "Acceptable use:",
        text: "You agree not to misuse the service — including uploading illegal content, attempting to reverse engineer the platform, or using it to harm others.",
      },
    ],
  },
  {
    title: "Uploaded content",
    items: [
      {
        label: "Ownership:",
        text: "You retain full ownership of any documents you upload. By uploading, you grant Socrate a limited licence to process your content solely to provide the service.",
      },
      {
        label: "Responsibility:",
        text: "You are solely responsible for the content you upload. Do not upload documents you do not have the right to share.",
      },
      {
        label: "Removal:",
        text: "We reserve the right to remove content that violates these terms or applicable law.",
      },
    ],
  },
  {
    title: "Payments & subscriptions",
    items: [
      {
        label: "Billing:",
        text: "Paid plans are billed monthly or annually. All payments are processed securely via Stripe.",
      },
      {
        label: "Refunds:",
        text: "We offer a 7-day refund policy for new subscriptions. After 7 days, payments are non-refundable.",
      },
      {
        label: "Cancellation:",
        text: "You can cancel your subscription at any time from Settings. You will retain access until the end of your billing period.",
      },
    ],
  },
  {
    title: "Intellectual property",
    items: [
      {
        label: "Our platform:",
        text: "All code, design, branding, and content created by Socrate is our intellectual property and may not be copied or reused without permission.",
      },
      {
        label: "AI output:",
        text: "Responses generated by the AI tutor are provided for personal study use only and should not be republished or resold.",
      },
    ],
  },
  {
    title: "Disclaimers",
    items: [
      {
        label: "No warranty:",
        text: "Socrate is provided 'as is'. We do not guarantee the accuracy of AI-generated responses. Always verify important information independently.",
      },
      {
        label: "Availability:",
        text: "We aim for high uptime but do not guarantee uninterrupted access. Scheduled maintenance will be communicated in advance where possible.",
      },
    ],
  },
  {
    title: "Limitation of liability",
    items: [
      {
        label: "Cap:",
        text: "To the fullest extent permitted by law, Socrate's liability is limited to the amount you paid us in the 12 months preceding the claim.",
      },
      {
        label: "Exclusions:",
        text: "We are not liable for indirect, incidental, or consequential damages arising from your use of the service.",
      },
    ],
  },
  {
    title: "Contact",
    items: [
      {
        label: "Questions?",
        text: "Email us at legal@socrate.ai — we respond within 48 hours.",
      },
    ],
  },
];

export default function Page() {
  return (
    <LegalPage
      title="Terms &amp; Conditions"
      updated="March 28, 2026"
      intro="Please read these terms carefully before using Socrate. By using the platform, you agree to be bound by them. We've kept it plain and simple — no legal walls."
      sections={sections}
    />
  );
}
